server:
  port: 8084

spring:
  application:
    name: ordercenter
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml
    typeAliasesPackage: com.example.*.entity
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8081/eureka/

rabbit:
  mq:
    host: localhost
    port: 5672
    username: liang
    password: 123456

rocketmq:
  producer:
    group: producer_my_test_message
  name-server: 127.0.0.1:9876